name: kazino
description: A new kazino Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_platform_widgets: ^0.32.2
  cupertino_icons: ^0.1.2
  rxdart: ^0.22.6
  flutter_range_slider: ^0.0.4
  flutter_svg: ^0.16.0
  align_positioned: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true