name: moneywheel
description: A new kazino Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_platform_widgets: ^0.60.2
  cupertino_icons: ^1.0.0
  rxdart: ^0.24.1
  flutter_range_slider: ^1.5.0
  flutter_svg: ^0.19.0
  align_positioned: ^1.2.8
  path_provider: ^1.6.14
  flutter_slidable: ^0.5.7

  firebase_core: ^0.5.0
  firebase_database: ^4.0.0
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/